apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-prod
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gcr.io/$route/myapp:v1   #Insert the specific route
        ports:
        - containerPort: 8888